services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/tank/arr:/data
      - ../config/sonarr:/config
    labels:
      glance.name: sonarr
      glance.icon: si:sonarr
      glance.url: https://sonarr.media.blackmesa.local
      glance.description: Sonarr is a PVR for torrent users
      glance.category: media
    restart: unless-stopped
    networks:
      exposed:
        ipv4_address: 172.30.0.161

networks:
  exposed:
    external: true
    name: blackmesa
