services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - GHOSTFOLIO_URL=${GHOSTFOLIO_URL}
      - GHOSTFOLIO_API_URL=${GHOSTFOLIO_API_URL}
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
    labels:
      glance.name: Glance
      glance.icon: sh:glance-light
      glance.url: https://glance.blackmesa.local
      glance.description: Costumizable dashboard
      glance.category: other
    restart: unless-stopped
    networks:
      exposed:
        ipv4_address: 172.30.0.120

networks:
  exposed:
    external: true
    name: blackmesa
