services:
  app:
    image: jc21/nginx-proxy-manager:2.12.6
    container_name: nginx
    environment:
      - DISABLE_IPV6=true
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped 
    networks:
      exposed:
        ipv4_address: 172.30.0.5

networks:
  exposed:
    external: true
    name: blackmesa
